// Uncomment as they're implemented. I know, kinda gross
export enum Day {
  One = 'one',
  Two = 'two',
  Three = 'three',
  Four = 'four',
  Five = 'five',
  Six = 'six',
  Seven = 'seven',
  // Eight = 'eight',
  // Nine = 'nine',
  // Ten = 'ten',
  // Eleven = 'eleven',
  // Twelve = 'twelve',
  // Thirteen = 'thirteen',
  // Fourteen = 'fourteen',
  // Fifteen = 'fifteen',
  // Sixteen = 'sixteen',
  // Seventeen = 'seventeen',
  // Eighteen = 'eighteen',
  // Nineteen = 'nineteen',
  // Twenty = 'twenty',
  // TwentyOne = 'twenty-one',
  // TwentyTwo = 'twenty-two',
  // TwentyThree = 'twenty-three',
  // TwentyFour = 'twenty-four',
  // TwentyFive = 'twenty-five',
}
